// frontend-react/src/components/LangMultiSelect.tsx
// ============================================================================
// components/LangMultiSelect.tsx — 目标语言多选（TDesign Select 分组 + 自定义语言）
// 功能等价 Vue 版：KB 九语分组 / 其他常用语分组 / 手输自定义语言代码加入选中集。
// ============================================================================
import { useEffect, useMemo, useState } from 'react'
import { Select, Input, Button } from 'tdesign-react'
import { t } from '@/i18n'

// KB 九语（与后端 /api/translation/langs 对齐的本地兜底；挂载后由父组件动态覆盖可选）
// 知识库支持的高质量目标语言（本地兜底，后端返回后覆盖名称与国旗）
const KB_LANGS: Array<{ code: string; label: string; flag?: string }> = [
  { code: 'en', label: '英语', flag: '🇬🇧' },
  { code: 'ru', label: '俄语', flag: '🇷🇺' },
  { code: 'ar', label: '阿拉伯语', flag: '🇸🇦' },
  { code: 'es', label: '西班牙语', flag: '🇪🇸' },
  { code: 'pt', label: '葡萄牙语', flag: '🇵🇹' },
  { code: 'fr', label: '法语', flag: '🇫🇷' },
  { code: 'kk', label: '哈萨克语', flag: '🇰🇿' },
  { code: 'de', label: '德语', flag: '🇩🇪' },
  { code: 'zh_hant', label: '繁体中文', flag: '🇹🇼' },
]

// 其他常用语言（非 KB，走 AI 翻译）分组选项
const OTHER_LANGS: Array<{ code: string; label: string; flag?: string }> = [
  { code: 'ja', label: '日语', flag: '🇯🇵' },
  { code: 'ko', label: '韩语', flag: '🇰🇷' },
  { code: 'th', label: '泰语', flag: '🇹🇭' },
  { code: 'vi', label: '越南语', flag: '🇻🇳' },
  { code: 'ms', label: '马来语', flag: '🇲🇾' },
  { code: 'id_lang', label: '印尼语', flag: '🇮🇩' },
  { code: 'it', label: '意大利语', flag: '🇮🇹' },
  { code: 'pl', label: '波兰语', flag: '🇵🇱' },
  { code: 'tr', label: '土耳其语', flag: '🇹🇷' },
]

// LangMultiSelect 入参：value 当前选中语言代码数组；onChange 变更回调；kbLangs 覆盖 KB 分组
interface Props {
  value: string[]
  onChange: (v: string[]) => void
  /** 覆盖 KB 分组选项（默认本地九语） */
  kbLangs?: string[]
}

// 默认导出组件：目标语言多选（分组 Select + 自定义语言输入），等价 Vue 版 LanguagePicker
export default function LangMultiSelect({ value, onChange, kbLangs }: Props) {
  const [custom, setCustom] = useState('')
  const [extraCodes, setExtraCodes] = useState<string[]>([])
  // 从后端加载 KB 支持语言（新语言升级进 KB 区，名称/国旗覆盖本地兜底）
  const [apiKb, setApiKb] = useState<Array<{ code: string; label: string; flag?: string }>>([])

  // 挂载时从后端拉取 KB 语言列表，覆盖/补充本地兜底选项
  useEffect(() => {
    ;(async () => {
      try {
        const resp = await fetch('/api/translation/langs')
        if (!resp.ok) return
        const data = await resp.json()
        if (data.kb_langs?.length) {
          setApiKb(data.kb_langs.map((l: any) => ({ code: l.code, label: l.name, flag: l.flag })))
        }
      } catch { /* 静默保留内置选项 */ }
    })()
  }, [])

  // 构造分组选项：KB 分组 + 其他语言分组 + 自定义语言分组（如有）
  const options = useMemo(() => {
    const kbSet = kbLangs?.length ? kbLangs : KB_LANGS.map((x) => x.code)
    const kbMap = new Map<string, { code: string; label: string; flag?: string }>()
    for (const x of [...KB_LANGS, ...apiKb]) kbMap.set(x.code, { ...(kbMap.get(x.code) || {}), ...x })
    const nameOf = (code: string): string => {
      const hit = [...kbMap.values(), ...OTHER_LANGS].find((x) => x.code === code)
      return hit ? `${hit.flag || ''} ${hit.label}` : code
    }
    return [
      {
        group: t('chat.kbGroup'),
        children: [...kbMap.values()].filter((x) => kbSet.includes(x.code))
          .map((x) => ({ label: `${x.flag || ''} ${x.label}`, value: x.code })),
      },
      {
        group: t('chat.otherGroup'),
        children: OTHER_LANGS.map((x) => ({ label: `${x.flag || ''} ${x.label}`, value: x.code })),
      },
      ...(extraCodes.length
        ? [{
            group: t('chat.customGroup'),
            children: extraCodes.map((c) => ({ label: nameOf(c), value: c })),
          }]
        : []),
    ]
  }, [kbLangs, extraCodes])

  // 将手输语言代码加入自定义分组与选中值
  function addCustom() {
    const code = custom.trim()
    if (!code || value.includes(code)) return
    setExtraCodes((prev) => (prev.includes(code) ? prev : [...prev, code]))
    onChange([...value, code])
    setCustom('')
  }

  // 自定义语言输入内嵌于下拉面板底部（与多选选项合并，不再单独外置）
  const customPanel = (
    <div
      style={{ padding: '8px 12px', borderTop: '1px solid #e7e7e7', display: 'flex', gap: 6, alignItems: 'center' }}
      onClick={(e) => e.stopPropagation()}
    >
      <Input size="small" style={{ flex: 1 }} value={custom}
             placeholder={t('chat.customLangPlaceholder')}
             onChange={(v) => setCustom(v as string)}
             onEnter={() => addCustom()} />
      <Button size="small" variant="outline" disabled={!custom.trim()} onClick={addCustom}>＋</Button>
    </div>
  )

  return (
    <Select
      multiple
      clearable
      filterable
      value={value}
      options={options as never}
      placeholder={t('chat.langPlaceholder')}
      onChange={(v) => onChange((v as string[]) || [])}
      panelBottomContent={customPanel}
      style={{ width: '100%' }}
    />
  )
}

// frontend/src/components/LangMultiSelect.vue
<!-- ============================================================================
   components/LangMultiSelect.vue — 多选目标语言选择器（与工作台同款交互）
   职责：🌐 按钮 + 下拉多选（知识库语言区 / 其他语言区 / 更多语言手输）；
   v-model 绑定语言代码数组；KB 语言列表从 /api/translation/langs 动态加载。
   ============================================================================ -->
<template>
  <div class="lms" ref="rootRef">
    <button type="button" class="lms-btn" @click.stop="open = !open">
      🌐 {{ btnLabel }}
    </button>
    <div v-if="open" class="lang-dropdown lms-dropdown">
      <div class="lang-section-title">{{ t('chat.kbLangs') }}</div>
      <label v-for="lang in kbLangs" :key="'kb-' + lang" class="lang-option">
        <input type="checkbox" :checked="modelValue.includes(lang)" @change="toggle(lang)" />
        <span>{{ LANG_OPTIONS[lang]?.flag || '🌐' }} {{ langLabel(lang, LANG_OPTIONS[lang]?.label) }}</span>
      </label>
      <div class="lang-divider"></div>
      <div class="lang-section-title">{{ t('chat.otherLangs') }}</div>
      <label v-for="olang in otherLangList" :key="'o-' + olang.code" class="lang-option">
        <input type="checkbox" :checked="modelValue.includes(olang.code)" @change="toggle(olang.code)" />
        <span>{{ olang.flag }} {{ langLabel(olang.code, olang.label) }}</span>
      </label>
      <div class="lang-divider" style="margin:4px 0"></div>
      <label class="lang-option">
        <input type="checkbox" :checked="modelValue.includes('other')" @change="toggle('other')" />
        <span>{{ t('chat.moreLangs') }}</span>
      </label>
      <div v-if="modelValue.includes('other')" class="lms-custom">
        <input v-model="customText" class="lang-custom-input" :placeholder="t('chat.customLangPlaceholder')" @keydown.enter.prevent="addCustom" />
        <button type="button" class="lms-add" @click="addCustom" :disabled="!customText.trim()">＋</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { t } from '@/i18n'

// v-model：已选语言代码数组
const props = defineProps<{ modelValue: string[] }>()
const emit = defineEmits<{ 'update:modelValue': [string[]] }>()

// KB 语言（默认兜底，挂载后从后端动态覆盖）
const kbLangs = ref<string[]>(['en', 'ru', 'ar', 'es', 'pt', 'fr', 'kk', 'de', 'zh_hant'])
// 语言名称/国旗映射（本地兜底）
const LANG_OPTIONS: Record<string, { label: string; flag: string }> = {
  en: { label: '英语', flag: '🇬🇧' }, ru: { label: '俄语', flag: '🇷🇺' },
  ar: { label: '阿拉伯语', flag: '🇸🇦' }, es: { label: '西班牙语', flag: '🇪🇸' },
  pt: { label: '葡萄牙语', flag: '🇵🇹' }, fr: { label: '法语', flag: '🇫🇷' },
  kk: { label: '哈萨克语', flag: '🇰🇿' }, de: { label: '德语', flag: '🇩🇪' },
  zh_hant: { label: '繁体中文', flag: '🇹🇼' },
}
// 其他 AI 翻译语言
const OTHER_LANG_OPTIONS = ref<Record<string, { label: string; flag: string }>>({
  ja: { label: '日语', flag: '🇯🇵' }, ko: { label: '韩语', flag: '🇰🇷' },
  th: { label: '泰语', flag: '🇹🇭' }, vi: { label: '越南语', flag: '🇻🇳' },
  ms: { label: '马来语', flag: '🇲🇾' }, id_lang: { label: '印尼语', flag: '🇮🇩' },
  it: { label: '意大利语', flag: '🇮🇹' }, pl: { label: '波兰语', flag: '🇵🇱' },
  tr: { label: '土耳其语', flag: '🇹🇷' },
})
const otherLangList = computed(() =>
  Object.entries(OTHER_LANG_OPTIONS.value).map(([code, info]) => ({ code, ...info }))
)

const open = ref(false)
const customText = ref('')
const rootRef = ref<HTMLElement | null>(null)

// 切换勾选（other 为「更多语言」开关位，不入数组）
function toggle(lang: string) {
  if (lang === 'other') return
  const sel = props.modelValue.includes(lang)
    ? props.modelValue.filter(l => l !== lang)
    : [...props.modelValue, lang]
  emit('update:modelValue', sel)
}

// 添加自定义语言
function addCustom() {
  const raw = customText.value.trim()
  if (!raw) return
  if (!props.modelValue.includes(raw)) {
    emit('update:modelValue', [...props.modelValue, raw])
  }
  customText.value = ''
}

// 显示名：优先 i18n lang.<code>，回退本地映射
function langLabel(code: string, fallback?: string): string {
  const v = t(`lang.${code}`)
  return v !== `lang.${code}` ? v : (fallback || code)
}

// 按钮标签：0=0语；≤2 展开名称；更多显示数量
const btnLabel = computed(() => {
  const sel = props.modelValue
  if (sel.length === 0) return t('chat.langZero')
  if (sel.length <= 2) {
    const names = sel.map(l => {
      if (l === 'other') return t('chat.langOther')
      return langLabel(l, LANG_OPTIONS[l]?.label || OTHER_LANG_OPTIONS.value[l]?.label)
    })
    return names.join('+')
  }
  return t('chat.langCount').replace('{n}', String(sel.length))
})

// 从后端加载 KB 支持的语言（新语言升级进 KB 区）
async function loadTranslationLangs() {
  try {
    const resp = await fetch('/api/translation/langs')
    if (!resp.ok) return
    const data = await resp.json()
    if (data.kb_langs?.length) {
      kbLangs.value = data.kb_langs.map((l: any) => l.code)
      for (const l of data.kb_langs) {
        if (!LANG_OPTIONS[l.code]) LANG_OPTIONS[l.code] = { label: l.name, flag: l.flag }
        else { LANG_OPTIONS[l.code].label = l.name; LANG_OPTIONS[l.code].flag = l.flag }
        if (OTHER_LANG_OPTIONS.value[l.code]) delete OTHER_LANG_OPTIONS.value[l.code]
      }
    }
  } catch { /* 静默保留内置选项 */ }
}

// 点击外部关闭下拉
function onClickOutside(e: MouseEvent) {
  if (rootRef.value && !rootRef.value.contains(e.target as Node)) open.value = false
}
onMounted(() => {
  loadTranslationLangs()
  document.addEventListener('click', onClickOutside)
})
onUnmounted(() => document.removeEventListener('click', onClickOutside))
</script>

<style scoped>
.lms { position: relative; display: inline-block; }
.lms-btn {
  border: 1px solid #d8dee6; background: #fff; border-radius: 8px;
  padding: 7px 14px; font-size: 14px; cursor: pointer;
}
.lms-btn:hover { border-color: #bdc1c6; }
.lms-dropdown {
  position: absolute; bottom: calc(100% + 6px); left: 0; min-width: 220px;
  background: #fff; border: 1px solid #dadce0; border-radius: 12px;
  box-shadow: 0 4px 16px rgba(0,0,0,.12); padding: 8px 0;
  z-index: 100; max-height: 360px; overflow-y: auto;
}
.lang-option { display: flex; align-items: center; gap: 8px; padding: 8px 16px; cursor: pointer; font-size: 13px; color: #202124; }
.lang-option:hover { background: #f1f3f4; }
.lang-option input[type="checkbox"] { width: 16px; height: 16px; accent-color: #1a73e8; }
.lang-divider { height: 1px; background: #e0e0e0; margin: 0 16px 4px; }
.lang-section-title { padding: 8px 16px 4px; font-size: 12px; font-weight: 600; color: #5f6368; }
.lms-custom { display: flex; align-items: center; gap: 6px; padding: 4px 12px 8px 40px; }
.lang-custom-input {
  flex: 1; border: 1px solid #d8dee6; border-radius: 6px; padding: 5px 8px; font-size: 12px;
}
.lms-add {
  border: none; background: #1a73e8; color: #fff; width: 24px; height: 24px;
  border-radius: 50%; cursor: pointer; font-size: 13px; line-height: 1;
}
.lms-add:disabled { opacity: .4; cursor: not-allowed; }
</style>
