// frontend/src/components/Bell.vue
<!-- ============================================================================
   components/Bell.vue — 站内信铃铛（通知中心入口）
   职责：未读红点轮询（30s）+ 下拉列表 + 单条/全部已读
   ============================================================================ -->
<template>
  <div class="bell-wrap" style="position:relative">
    <button class="clear-btn" :title="t('bell.title')" @click="open = !open; open && load()">
      🔔<span v-if="unread > 0" class="bell-badge">{{ unread > 99 ? '99+' : unread }}</span>
    </button>
    <div v-if="open" class="bell-drop">
      <div class="ad-row" style="justify-content:space-between;padding:6px 10px;border-bottom:1px solid #eee">
        <b>{{ t('bell.title') }}</b>
        <button class="ad-btn-sm" @click="readAll">{{ t('bell.readAll') }}</button>
      </div>
      <div class="bell-list">
        <div v-for="n in list" :key="n.id" :class="['bell-item', n.read_at ? '' : 'unread']" @click="onItemClick(n)">
          <b style="font-size:13px">{{ n.title }}</b>
          <div class="ad-hint" style="margin:2px 0 0">{{ n.body }}</div>
          <div class="ad-hint" style="font-size:11px">{{ fmtTime(n.created_at) }}</div>
        </div>
        <div v-if="!list.length" class="ad-empty" style="padding:16px">{{ t('bell.empty') }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { gotoFeedbackPanel } from './admin/store'
import { ref, onMounted, onUnmounted } from 'vue'
import { notifications, notificationsUnread, notificationRead, notificationsReadAll } from '@/api'
import { t } from '@/i18n'
import { fmtTime } from './admin/ui'

// 下拉显隐 / 未读数 / 列表数据
const open = ref(false)
const unread = ref(0)
const list = ref<any[]>([])
let timer: number | undefined

// 拉取未读数（轮询）
// poll 轮询未读数（30s 周期）
async function poll() {
  try {
    const r = await notificationsUnread()
    if (r.success) unread.value = (r as any).unread || 0
  } catch {}
}

// 拉取列表
// load 拉取站内信列表
async function load() {
  const r = await notifications()
  if (r.success) list.value = (r as any).notifications || []
}

// 单条已读 + 反馈类跳转问题反馈面板
async function readOne(n: any) {
  if (!n.read_at) {
    await notificationRead(n.id)
    n.read_at = new Date().toISOString()
    unread.value = Math.max(0, unread.value - 1)
  }
  // ★ feedback 类通知 → 跳转「问题反馈」面板并定位该条
  if (n.ref_type === 'feedback') gotoFeedbackPanel(n.ref_id)
}
function onItemClick(n: any) { readOne(n); open.value = false }

// 全部已读
// readAll 全部标记已读并刷新
async function readAll() {
  await notificationsReadAll()
  await Promise.all([load(), poll()])
}

onMounted(() => { poll(); timer = window.setInterval(poll, 30000) })
onUnmounted(() => { if (timer) clearInterval(timer) })
</script>

<style scoped>
.bell-badge {
  position: absolute; top: -4px; right: -6px;
  background: #e74c3c; color: #fff; border-radius: 8px;
  font-size: 10px; padding: 0 4px; line-height: 14px;
}
.bell-drop {
  position: absolute; right: 0; top: 34px; width: 320px; max-height: 420px;
  background: #fff; border: 1px solid #e3e3e3; border-radius: 8px;
  box-shadow: 0 8px 24px rgba(0,0,0,.12); z-index: 50; overflow: hidden;
}
.bell-list { max-height: 360px; overflow: auto; }
.bell-item { padding: 8px 12px; cursor: pointer; border-bottom: 1px solid #f2f2f2; }
.bell-item:hover { background: #f7f9fc; }
.bell-item.unread { background: #fff8e6; }
</style>

// frontend-react/src/components/Bell.tsx
// ============================================================================
// components/Bell.tsx — 站内通知铃铛（TDesign Badge + Popup）
// 行为对齐：30s 未读轮询、下拉列表、单条已读/全部已读、feedback 类跳转后台反馈面板。
// ============================================================================
import { useCallback, useEffect, useRef, useState } from 'react'
import { Badge, Popup, Button, Empty } from 'tdesign-react'
import { notificationsUnread, notifications, notificationRead, notificationsReadAll } from '@/api'
import { fmtTime } from '@/lib/ui'
import { t } from '@/i18n'
import { useAdmin } from '@/stores/admin'

// 站内通知条目数据结构
interface NoticeItem {
  id: number
  title: string
  body: string
  ref_type?: string
  ref_id?: number
  created_at: string
}

// 默认导出组件：通知铃铛，负责未读轮询、下拉列表与已读操作（等价 Vue Bell.vue）
export default function Bell() {
  const [unread, setUnread] = useState(0)
  const [items, setItems] = useState<NoticeItem[]>([])
  const [open, setOpen] = useState(false)
  const { gotoPanel, isSuper, openFeedback } = useAdmin()
  const timerRef = useRef<number | null>(null)

  // 刷新未读数；下拉展开时同步拉取最近 20 条通知列表
  const refresh = useCallback(async () => {
    try {
      const u = await notificationsUnread()
      if (u.success) setUnread(Number((u as unknown as { unread?: number }).unread || 0))
      if (open) {
        const r = await notifications()
        if (r.success) setItems(((r as unknown as { notifications?: NoticeItem[] }).notifications || []).slice(0, 20))
      }
    } catch { /* 忽略 */ }
  }, [open])

  // 挂载即刷新并启动 30s 未读轮询；卸载时清除定时器
  useEffect(() => {
    void refresh()
    timerRef.current = window.setInterval(refresh, 30000)
    return () => { if (timerRef.current) window.clearInterval(timerRef.current) }
  }, [refresh])

  // 标记单条已读并刷新列表
  async function markRead(id: number) {
    await notificationRead(id)
    void refresh()
  }
  // 标记全部已读并刷新列表
  async function markAll() {
    await notificationsReadAll()
    void refresh()
  }

  // 点击通知：先标记已读，再按类型跳转（feedback→超管反馈面板，其余→工单页）
  function onItemClick(n: NoticeItem) {
    void markRead(n.id)
    // feedback 类通知 → 超管打开反馈处理面板；其余跳转工单
    if (isSuper && n.ref_type === 'feedback') openFeedback(n.ref_id as number)
    else gotoPanel('tickets')
    setOpen(false)
  }

  return (
    <Popup
      trigger="click"
      placement="bottom-right"
      showArrow
      visible={open}
      onVisibleChange={(v) => { setOpen(v as boolean); if (v) void refresh() }}
      content={
        <div style={{ width: 340, maxHeight: 420, overflowY: 'auto', padding: 8 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
            <b style={{ fontSize: 13 }}>{t('bell.title')}</b>
            <Button size="small" variant="text" onClick={markAll}>{t('bell.readAll')}</Button>
          </div>
          {items.length === 0 && <Empty description={t('bell.empty')} />}
          {items.map((n) => (
            <div key={n.id}
                 onClick={() => onItemClick(n)}
                 style={{ padding: '8px 6px', borderBottom: '1px solid #f0f2f7', cursor: 'pointer' }}>
              <div style={{ fontWeight: 600, fontSize: 13 }}>{n.title}</div>
              <div style={{ fontSize: 12, color: '#667', marginTop: 2, whiteSpace: 'pre-wrap' }}>{n.body}</div>
              <div style={{ fontSize: 11, color: '#99a', marginTop: 2 }}>{fmtTime(n.created_at)}</div>
            </div>
          ))}
        </div>
      }
    >
      <span style={{ cursor: 'pointer', display: 'inline-flex', padding: 6 }}>
        <Badge count={unread} dot={false} size="medium">🔔</Badge>
      </span>
    </Popup>
  )
}
