// frontend/src/components/SkillBadge.vue
<!-- ============================================================================
   components/SkillBadge.vue — 技能徽章组件
   职责：在 AI 回复气泡顶部显示当前技能标识（目前固定展示"🌐 翻译"）
   ============================================================================ -->
<template>
  <!-- 技能徽章：翻译 -->
  <span class="skill-badge">🌐 {{ t('chat.skillLabel') }}</span>
</template>

<script setup lang="ts">
import { t } from '@/i18n'
</script>

<style scoped>
/* 技能徽章样式：绿色圆角小标签 */
.skill-badge {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px;
  background: rgba(46, 125, 50, 0.12);
  color: #2e7d32;
  font-weight: 500;
}
</style>

// frontend-react/src/components/SkillBadge.tsx
// ============================================================================
// components/SkillBadge.tsx — 技能徽章（等价 Vue SkillBadge.vue）
// 职责：在 AI 回复气泡顶部显示当前技能标识（固定展示"🌐 翻译"）
// ============================================================================
import { t } from '@/i18n'

export interface SkillBadgeProps {
  skill?: string
}

export function SkillBadge(_props: SkillBadgeProps) {
  // 固定展示"🌐 翻译"技能标识（当前版本仅翻译一种技能，参数预留扩展）
  return <span className="skill-badge">🌐 {t('chat.skillLabel')}</span>
}

export default SkillBadge
